package me.danielstiner.dumble.mumble.net

import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.io.IOException
import java.nio.file.Files
import java.nio.file.StandardCopyOption
import kotlin.time.measureTimedValue

/** Where the app's [ClientIdentity] comes from. */
interface ClientIdentityStore {
    /** The identity, generated and saved on first call. Null only from [NoClientIdentity]. */
    suspend fun load(): ClientIdentity?
}

/** For tests, and any build that presents no certificate. */
object NoClientIdentity : ClientIdentityStore {
    override suspend fun load(): ClientIdentity? = null
}

/**
 * One identity per install, kept in [file] as the PKCS#12 [ClientIdentity.encode] writes. Read
 * once per process; generated by the first load, which the app starts at launch so the seconds of
 * RSA are not charged to the first connect. A file that no longer decodes fails every load, and
 * with it every connect, rather than being quietly replaced: the bytes stay for a fix to recover.
 *
 * Auto Backup carries the file to a reinstall or a new phone: it must stay under `filesDir` and
 * out of any backup exclusion.
 */
class FileClientIdentityStore(private val file: File) : ClientIdentityStore {

    // Two loads racing on a fresh install would otherwise each generate, and the memo could
    // hold one identity while the file holds the other.
    private val mutex = Mutex()
    @Volatile private var loaded: ClientIdentity? = null

    override suspend fun load(): ClientIdentity = loaded ?: mutex.withLock {
        loaded ?: withContext(Dispatchers.IO) { readOrCreate() }.also { loaded = it }
    }

    private fun readOrCreate(): ClientIdentity {
        // length() is 0 for a missing file and for an empty one, which a restore or a crash can
        // leave behind: no identity in it to keep, so it is generated over like a missing file.
        if (file.length() > 0L) {
            val bytes = file.readBytes()
            return try {
                ClientIdentity.decode(bytes)
            } catch (e: Exception) {
                // The message is what the connect screen shows: BouncyCastle's own is anything
                // from a MAC failure to a bare ClassCastException.
                throw IOException("client identity ${file.name} does not decode; clearing the app's data starts a new one", e)
            }
        }
        val (identity, took) = measureTimedValue { ClientIdentity.generate() }
        // Synced before the rename so a power loss leaves the old file or none, never a torn
        // file at the final name.
        val tmp = File(file.path + ".tmp")
        try {
            FileOutputStream(tmp).use { out ->
                out.write(identity.encode())
                out.fd.sync()
            }
            Files.move(tmp.toPath(), file.toPath(), StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING)
        } finally {
            tmp.delete()   // a partial write; nothing is left after a completed move
        }
        Log.i(TAG, "generated client identity sha1=${identity.hash} in $took")
        return identity
    }

    private companion object {
        const val TAG = "ClientIdentity"
    }
}
